# Generated by Django 5.0.3 on 2024-04-17 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_rename_firstname_student1_fullname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student1',
            name='password',
        ),
    ]
