# Generated by Django 5.0.3 on 2024-04-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_remove_student1_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student1',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
